#!/bin/sh
#
# $FreeBSD: $
#

# PROVIDE: mazacoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# mazacoin_enable (bool):	Set to NO by default.
#				Set it to YES to enable mazacoin.
# mazacoin_config (path):	Set to /usr/local/etc/mazacoin.conf
#				by default.
# mazacoin_user:	The user account mazacoin daemon runs as
#				It uses 'root' user by default.
# mazacoin_group:	The group account mazacoin daemon runs as
#				It uses 'wheel' group by default.
# mazacoin_datadir (str):	Default to "/var/db/mazacoin"
#				Base data directory.

. /etc/rc.subr

name=mazacoin
rcvar=mazacoin_enable

load_rc_config $name

: ${mazacoin_enable:=NO}
: ${mazacoin_config=/data/nodes/db/maza/mazacoin.conf}
: ${mazacoin_datadir=/data/nodes/db/maza}
: ${mazacoin_user="root"}
: ${mazacoin_group="wheel"}

required_files=${mazacoin_config}
command=/usr/local/bin/mazacoind
cli_command=/usr/local/bin/mazacoin-cli
mazacoin_chdir=${mazacoin_datadir}
pidfile="${mazacoin_datadir}/mazacoind.pid"
stop_cmd=mazacoin_stop
command_args="-conf=${mazacoin_config} -datadir=${mazacoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"
reindex_cmd=mazacoin_reindex
extra_commands="reindex"

mazacoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${mazacoin_datadir}
	[ $? -eq 0 ] && chown -R ${mazacoin_user}:${mazacoin_group} ${mazacoin_datadir}
	ln -s ${mazacoin_datadir} /.mazacoin
}

mazacoin_prestart()
{
	if [ ! -d "${mazacoin_datadir}/." ]; then
		mazacoin_create_datadir || return 1
	fi
}

mazacoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

mazacoin_stop()
{
    mazacoin_requirepidfile

	echo "Stopping ${name}."
	eval ${cli_command} -conf=${mazacoin_config} -datadir=${mazacoin_datadir} stop
	wait_for_pids ${rc_pid}
}

mazacoin_reindex()
{
	if [ -z "$rc_fast" -a -n "$rc_pid" ]; then
	    mazacoin_stop
	fi

	echo "Reindexing ${name} blockchain."
	command_args="${command_args} -reindex"
	eval ${command} ${command_args}
}

run_rc_command "$1"
