#!/bin/sh
#
# $FreeBSD: $
#

# PROVIDE: peercoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# peercoin_enable (bool):	Set to NO by default.
#				Set it to YES to enable peercoin.
# peercoin_config (path):	Set to /usr/local/etc/peercoin.conf
#				by default.
# peercoin_user:	The user account peercoin daemon runs as
#				It uses 'root' user by default.
# peercoin_group:	The group account peercoin daemon runs as
#				It uses 'wheel' group by default.
# peercoin_datadir (str):	Default to "/var/db/peercoin"
#				Base data directory.

. /etc/rc.subr

name=peercoin
rcvar=peercoin_enable

load_rc_config $name

: ${peercoin_enable:=NO}
: ${peercoin_config=/data/nodes/db/peercoin/peercoin.conf}
: ${peercoin_datadir=/data/nodes/db/peercoin}
: ${peercoin_user="root"}
: ${peercoin_group="wheel"}

required_files=${peercoin_config}
command=/usr/local/bin/peercoind
peercoin_chdir=${peercoin_datadir}
pidfile="${peercoin_datadir}/peercoind.pid"
stop_cmd=peercoin_stop
command_args="-conf=${peercoin_config} -datadir=${peercoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

peercoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${peercoin_datadir}
	[ $? -eq 0 ] && chown -R ${peercoin_user}:${peercoin_group} ${peercoin_datadir}
	ln -s ${peercoin_datadir} /.peercoin
}

peercoin_prestart()
{
	if [ ! -d "${peercoin_datadir}/." ]; then
		peercoin_create_datadir || return 1
	fi
}

peercoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

peercoin_stop()
{
    peercoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${peercoin_config} -datadir=${peercoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
