#!/bin/sh
#
# $FreeBSD: $
#

# PROVIDE: asiacoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# asiacoin_enable (bool):	Set to NO by default.
#				Set it to YES to enable asiacoin.
# asiacoin_config (path):	Set to /usr/local/etc/asiacoin.conf
#				by default.
# asiacoin_user:	The user account asiacoin daemon runs as
#				It uses 'root' user by default.
# asiacoin_group:	The group account asiacoin daemon runs as
#				It uses 'wheel' group by default.
# asiacoin_datadir (str):	Default to "/var/db/asiacoin"
#				Base data directory.

. /etc/rc.subr

name=asiacoin
rcvar=asiacoin_enable

load_rc_config $name

: ${asiacoin_enable:=NO}
: ${asiacoin_config=/data/nodes/db/asiacoin/asiacoin.conf}
: ${asiacoin_datadir=/data/nodes/db/asiacoin}
: ${asiacoin_user="root"}
: ${asiacoin_group="wheel"}

required_files=${asiacoin_config}
command=/usr/local/bin/asiacoind
cli_command=/usr/local/bin/asiacoin-cli
asiacoin_chdir=${asiacoin_datadir}
pidfile="${asiacoin_datadir}/asiacoind.pid"
stop_cmd=asiacoin_stop
command_args="-conf=${asiacoin_config} -datadir=${asiacoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"
reindex_cmd=asiacoin_reindex
extra_commands="reindex"

asiacoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${asiacoin_datadir}
	[ $? -eq 0 ] && chown -R ${asiacoin_user}:${asiacoin_group} ${asiacoin_datadir}
	ln -s ${asiacoin_datadir} /.asiacoin
}

asiacoin_prestart()
{
	if [ ! -d "${asiacoin_datadir}/." ]; then
		asiacoin_create_datadir || return 1
	fi
}

asiacoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

asiacoin_stop()
{
    asiacoin_requirepidfile

	echo "Stopping ${name}."
	eval ${cli_command} -conf=${asiacoin_config} -datadir=${asiacoin_datadir} stop
	wait_for_pids ${rc_pid}
}

asiacoin_reindex()
{
	if [ -z "$rc_fast" -a -n "$rc_pid" ]; then
	    asiacoin_stop
	fi

	echo "Reindexing ${name} blockchain."
	command_args="${command_args} -reindex"
	eval ${command} ${command_args}
}

run_rc_command "$1"
